#!/usr/bin/env bash
# script to install nginx
apt-get -y update
apt-get -y install nginx
echo "server {
    listen 80;
    location / {
        echo \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default
service nginx restart
