#!/usr/bin/env bash
# Get the list of directories in /proc that represent running processes
process_dirs=$(find /proc -maxdepth 1 -type d -name '[0-9]*' 2>/dev/null)

for dir in $process_dirs; do
  pid=$(basename "$dir")

  process_name=$(tr '\0' ' ' < "$dir/cmdline" | awk '{print $1}')

  if [[ "$process_name" == *"bash"* ]]; then
    echo "$pid $process_name"
  fi
done
