#!/usr/bin/env bash
# Find the process ID (PID) of 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n "$pid" ]]; then
  kill "$pid"
  echo "Process stopped"
else
  echo "Process not found"
fi
