#!/usr/bin/env bash
#To infinity and beyond indefinitely
function handle_sigterm {
  echo "I am invincible!!!"
  exit
}

trap handle_sigterm SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
