#!/usr/bin/env bash

# Find the process ID (PID) of 7-highlander
pid=$(pgrep -f "7-highlander")

if [[ -n "$pid" ]]; then
  # Send the termination signal to the process
  kill "$pid"
  echo "Process killed"
else
  echo "Process not found"
fi
