#!/usr/bin/env bash
#script to run nginx as nginx user

pkill apache2
# Update the nginx configuration to run as the nginx user
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
